//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mv
{
    using System;
    using System.Collections.Generic;
    
    public partial class Complaints
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Complaints()
        {
            this.BlackList = new HashSet<BlackList>();
        }
    
        public long ID { get; set; }
        public System.DateTime Datetime { get; set; }
        public byte[] Kind { get; set; }
        public bool PostOrUser { get; set; }
        public long ToComplainID { get; set; }
        public long ComplainerID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BlackList> BlackList { get; set; }
        public virtual Users Users { get; set; }
    }
}
