//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mv
{
    using System;
    using System.Collections.Generic;
    
    public partial class Messages
    {
        public long ID { get; set; }
        public System.DateTime Datetime { get; set; }
        public bool SendOrReceive { get; set; }
        public string Message { get; set; }
        public int ConversationID { get; set; }
    
        public virtual Conversations Conversations { get; set; }
    }
}
