//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mv
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rates
    {
        public int ID { get; set; }
        public string PictureLoc { get; set; }
        public byte StarPoint { get; set; }
        public int RateCount { get; set; }
        public long UserID { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
